num_tr = 86298;
num_job = 20;
tr_perjob = round(num_tr/num_job);
for i = 1 : num_job
    fileID = fopen(['/home-4/stan26@jhu.edu/scratch/Synthetic_data/job' num2str(i) '.sh'], 'w');
    if (i ) * tr_perjob < num_tr
        end_range = (i ) * tr_perjob;
    else
        end_range = num_tr;
    end
txt =[ '#!/bin/bash -l \n ' ...
'#SBATCH --job-name=CT' num2str(i) ' \n' ...
'#SBATCH --time=70:00:00 \n' ...
'#SBATCH --partition=shared \n'...
'#SBATCH --nodes=1 \n'...
'#SBATCH --cpus-per-task=2 \n' ...
'#SBATCH --mail-type=end \n' ...
'#SBATCH --mail-user=stan26@jhu.edu \n' ...
'ml matlab \n' ...
'cd ~/work/Code/LocalCode/MATLAB/Post_analysis/ \n' ...
'matlab -nodisplay << EOF \n' ...
'tracks_cd_map = memmapfile(''/home-4/stan26@jhu.edu/scratch/Synthetic_data/track_cd_bin.mat'', ''Format'',{''double'',[67905821 5],''tracks''}); \n' ...
'tracks_orig_map = memmapfile(''/home-4/stan26@jhu.edu/scratch/Synthetic_data/track_orig_bin.mat'', ''Format'',{''double'',[75000000 5],''tracks''}); \n' ...
'[fit_percent, fit, correctness] = CompareTracks(tracks_orig_map, tracks_cd_map, 0, ''/home-4/stan26@jhu.edu/scratch/Synthetic_data/compare' num2str(i)  '.mat'', [' num2str((i - 1) * tr_perjob + 1)  ',' num2str(end_range)  ']); \n'...
'EOF \n'];
fprintf(fileID, txt);
fclose(fileID);
system(['sbatch /home-4/stan26@jhu.edu/scratch/Synthetic_data/job' num2str(i) '.sh']);
end
