datapath = '/home-4/stan26@jhu.edu/scratch/BubbleData/ProcessedTracks/';
files = {'04.14.18', '04.15.18'};
Bubble_data = 1;
filepath = [];
if Bubble_data
    for i = 1 : size(files, 2)
        folders = dir([datapath files{i} '/Run*']);
        for j = 1 : size(folders, 1)
            subfolders = dir([datapath files{i} '/' folders(j).name '/Bubble*']);
            for k = 1 : size(subfolders, 1)
                filepath = [filepath;  
                    {[datapath files{i} '/' folders(j).name '/' subfolders(k).name '/']}];
            end
        end
    end
end
mkdir([datapath 'Jobs/']);
mkdir([datapath 'SmoothTrackswithVel/']);
filepath = filepath';

num_files = size(filepath, 2);
for i = 1 : num_files
    filename = erase(erase(extractAfter(filepath{i}, 'ProcessedTracks/'), '/'), '.');
    fileID = fopen([datapath 'Jobs/' filename  '.sh'],'w');
    txt = [ '#!/bin/bash -l \n' ...
    '#SBATCH --job-name=' filename '\n' ...
    '#SBATCH --time=72:00:00 \n' ... 
    '#SBATCH --nodes=1 \n' ...
    '#SBATCH --cpus-per-task=5 \n' ...
    '#SBATCH --partition=shared \n' ...
    '#SBATCH --mem=100000MB \n' ...
    '#SBATCH --mail-type=end \n' ...
    '#SBATCH --mail-user=stan26@jhu.edu\n' ...
    '\n' ...
    '#run your job \n' ...
    'module load matlab \n' ...
    'matlab -nodisplay > ' datapath 'Jobs/result_'  filename '.txt << EOF\n' ...
    'cd ~/work/Code/LocalCode/MATLAB/Post_analysis/ \n' ...
    'datapath = ''' filepath{i} ''';\n' ...
    '[filter_data, mean_data] = CalVelAcc(datapath);\n' ...
    'save ' datapath 'SmoothTrackswithVel/' filename '.mat' ' filter_data mean_data -v7.3\n' ...
    'EOF\n'];
    fprintf(fileID, txt);
    fclose(fileID);
    system(['sbatch ' datapath 'Jobs/' filename  '.sh']);
end
