datapath = '/home-4/stan26@jhu.edu/scratch/2018-11-11/Run2/Tracks/ConvergedTracks/';
num_files = 1;
mkdir([datapath, 'StructFunction']);
mkdir([datapath, 'Jobs']);



for i = 1 : num_files
    filename = extractAfter(datapath, 'scratch/');
    fileID = fopen([datapath 'Jobs/' erase(extractBefore(filename, '/Tracks'), '/')  '.sh'],'w');
    txt = [ '#!/bin/bash -l \n' ...
    '#SBATCH --job-name=' erase(extractBefore(filename, '/Tracks'), '/') '\n' ...
    '#SBATCH --time=72:00:00 \n' ... 
    '#SBATCH --nodes=1 \n' ...
    '#SBATCH --cpus-per-task=24 \n' ...
    '#SBATCH --partition=shared \n' ...
    '#SBATCH --mem=100000MB \n' ...
    '#SBATCH --mail-type=end \n' ...
    '#SBATCH --mail-user=stan26@jhu.edu\n' ...
    '\n' ...
    '#run your job \n' ...
    'module load matlab \n' ...
    'matlab -nodisplay > ' datapath 'Jobs/result_'  erase(extractBefore(filename, '/Tracks'), '/') '.txt << EOF\n' ...
    'cd ~/work/Code/LocalCode/MATLAB/Post_analysis/ \n' ...
    'datapath = ''' datapath ''';\n'...
    'redges_lin = 0.1:0.3:60;\n'...
    '[statistics_struct, statistics_corr] = CalStructFun(datapath, 150);\n' ...
    'EOF\n'];
    fprintf(fileID, txt);
    fclose(fileID);
    system(['sbatch ' datapath 'Jobs/' erase(extractBefore(filename, '/Tracks'), '/')  '.sh']);
end
