function map = BinMap(x, y, dx)
xmin = min(x);
%dx = (max(x) - xmin) / nbin;
nbin = length(dx) - 1;
map = [];
for i = 1 : nbin
%     x_l = xmin + (i - 1) * dx;
%     x_u = xmin + i * dx;
    x_l = dx(i);
    x_u = dx(i + 1);
    xx = (x_l + x_u) / 2;
    yy = y(x > x_l & x < x_u);
%     [C,~,ic] = unique(yy);
%     a_counts = accumarray(ic,1); 
    h = histogram(yy);
    cn = h.Values;
    cr = h.BinEdges(2:end);
    y_mean(i) = mean(yy);
    
%     map = [map; [ones(length(C),1) * xx, C, a_counts / sum(a_counts)]];
    map = [map; [ones(length(cr),1) * xx, cr', cn' / sum(cn)]];
end
createfigure(map(:,1), map(:,2), [] , map(:,3));
hold on
plot(dx(2:end), y_mean)
end

function createfigure(X1, Y1, S1, C1)
%CREATEFIGURE(X1, Y1, S1, C1)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c

%  Auto-generated by MATLAB on 10-Dec-2019 15:53:40

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,S1,C1,'MarkerFaceColor','flat','MarkerEdgeColor','none');

box(axes1,'on');
% Set the remaining axes properties
% set(axes1,'ColorScale','log','FontSize',18,'LineWidth',2,'XMinorTick','on',...
%    'YMinorTick','on','YScale','log');
set(axes1,'FontSize',18,'LineWidth',2,'XMinorTick','on',...
    'YMinorTick','on');
% Create colorbar
colorbar(axes1,'LineWidth',2);
end