% [R, pairs, disp_matrix] = PairDispersion2(data_map, [0.1 0.5]*0.15);
% save([data_path '0-05kol.mat'], 'data_map','disp_matrix','pairs', 'R');

% [R, pairs, disp_matrix] = PairDispersion2(data_map, [0.5 1]*0.15);
% save([data_path '05-1kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [0.1 2] * len_kol, disp_rate);
save([data_path '1-2kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [2 3]*len_kol, disp_rate);
save([data_path '2-3kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [3 4]*len_kol, disp_rate);
save([data_path '3-4kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [4 5]*len_kol, disp_rate);
save([data_path '4-5kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [5 7]*len_kol, disp_rate);
save([data_path '5-7kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [7 9]*len_kol, disp_rate);
save([data_path '7-9kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [9 11]*len_kol, disp_rate);
save([data_path '9-11kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [11 13]*len_kol, disp_rate);
save([data_path '11-13kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [13 15]*len_kol, disp_rate);
save([data_path '13-15kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [1 5]*len_kol, disp_rate);
save([data_path '0-5kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [5 10]*len_kol, disp_rate);
save([data_path '5-10kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [10 15]*len_kol, disp_rate);
save([data_path '10-15kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [15 20]*len_kol, disp_rate);
save([data_path '15-20kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [20 25]*len_kol, disp_rate);
save([data_path '20-25kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [25 30]*len_kol, disp_rate);
save([data_path '25-30kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [45 50]*len_kol, disp_rate);
save([data_path '45-50kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [95 100]*len_kol, disp_rate);
save([data_path '95-100kol.mat'], 'data_map','disp_matrix','pairs', 'R');
[R, pairs, disp_matrix] = PairDispersion2(data_map, [195 200]*len_kol, disp_rate);
save([data_path '195-200kol.mat'], 'data_map','disp_matrix','pairs', 'R');